apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  labels:
    type: local
    app: mysql
    tier: database
type: Opaque
data:
  password: cGFzc3dvcmQ=
  user: d29yZHByZXNz
  database: d29yZHByZXNz
